//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommProtocolApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Datax
    {
        public Nullable<int> id { get; set; }
        public int Word1 { get; set; }
        public Nullable<int> Word2 { get; set; }
        public Nullable<int> Word3 { get; set; }
        public Nullable<int> Word4 { get; set; }
        public Nullable<int> Word5 { get; set; }
        public Nullable<int> Word6 { get; set; }
        public Nullable<int> Word7 { get; set; }
        public Nullable<int> Word8 { get; set; }
        public Nullable<int> Word9 { get; set; }
        public Nullable<int> Int1 { get; set; }
        public Nullable<int> Int2 { get; set; }
        public Nullable<int> Int3 { get; set; }
        public Nullable<int> Int4 { get; set; }
        public Nullable<int> Int5 { get; set; }
        public Nullable<int> Int6 { get; set; }
        public Nullable<int> Int7 { get; set; }
        public Nullable<int> Int8 { get; set; }
        public Nullable<int> Int9 { get; set; }
        public Nullable<float> Real1 { get; set; }
        public Nullable<float> Real2 { get; set; }
        public Nullable<float> Real3 { get; set; }
        public Nullable<float> Real4 { get; set; }
        public Nullable<float> Real5 { get; set; }
        public Nullable<float> Real6 { get; set; }
        public Nullable<float> Real7 { get; set; }
        public Nullable<float> Real8 { get; set; }
        public Nullable<float> Real9 { get; set; }
        public Nullable<bool> Bool1 { get; set; }
        public Nullable<bool> Bool2 { get; set; }
        public Nullable<bool> Bool3 { get; set; }
        public Nullable<bool> Bool4 { get; set; }
        public Nullable<bool> Bool5 { get; set; }
        public Nullable<bool> Bool6 { get; set; }
        public Nullable<bool> Bool7 { get; set; }
        public Nullable<bool> Bool8 { get; set; }
        public Nullable<bool> Bool9 { get; set; }
    }
}
