//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommProtocolApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKullanici
    {
        public int KullaniciId { get; set; }
        public string KullaniciAd { get; set; }
        public string KullaniciSifre { get; set; }
        public Nullable<int> KullaniciFirma { get; set; }
    
        public virtual TblFirma TblFirma { get; set; }
    }
}
