//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommProtocolApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMuh
    {
        public int MuhId { get; set; }
        public string MuhAdSoyad { get; set; }
        public string MuhMail { get; set; }
        public string MuhSifre { get; set; }
        public string MuhPhone { get; set; }
        public Nullable<int> MuhDepartment { get; set; }
        public string MuhAdres { get; set; }
        public string MuhDurum { get; set; }
        public string MuhAciklama { get; set; }
    
        public virtual TBLDep TBLDep { get; set; }
        public virtual TBLProje TBLProje { get; set; }
    }
}
