//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommProtocolApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLProje
    {
        public int ProjeId { get; set; }
        public string ProjeAd { get; set; }
        public Nullable<int> ProjeSehir { get; set; }
        public Nullable<int> ProjeMuh { get; set; }
        public Nullable<int> ProjeProtokol { get; set; }
        public string ProjeAciklama { get; set; }
        public string ProjeDurum { get; set; }
    
        public virtual TBLProtokol TBLProtokol { get; set; }
        public virtual TBLSehir TBLSehir { get; set; }
        public virtual TBLMuh TBLMuh { get; set; }
    }
}
